# Generated by Django 3.1.6 on 2021-02-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=models.JSONField(default='{}', unique=True),
        ),
    ]
