# Generated by Django 3.1.6 on 2021-02-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.JSONField(default='dict', unique=True),
        ),
    ]
