# Generated by Django 3.1.6 on 2021-03-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_location_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='machines',
            field=models.JSONField(default=list),
        ),
    ]
